# Speed Dating with Tinder — Analyse Exploratoire

Données issues d'expériences de speed dating (2002–2004). Chaque ligne représente un échange de 4 minutes entre deux participants. L'objectif : comprendre ce qui pousse deux personnes à vouloir se revoir.

**5 questions à explorer :**
1. Quels sont les attributs les moins désirables selon le genre ?
2. L'attractivité est-elle aussi décisive qu'on le croit ?
3. Les intérêts partagés comptent-ils plus que l'origine raciale ?
4. Les participants se connaissent-ils eux-mêmes ?
5. Vaut-il mieux passer en début ou en fin de soirée ?

## Setup

In [1]:
import pandas as pd
import plotly.express as px

pd.set_option('display.max_columns', None)

## Chargement des données

In [2]:
df = pd.read_csv("../data/raw/Speed_Dating_Data.csv", encoding='latin-1')
print(f"{df.shape[0]} speed dates — {df.shape[1]} variables")
df.head()

8378 speed dates — 195 variables

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field,field_cd,undergra,mn_sat,tuition,race,imprace,imprelig,from,zipcode,income,goal,date,go_out,career,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
0,1,1.0,0,1,1,1,10,7,NaN,4,1,11.0,0,0.14,0,27.0,2.0,35.0,20.0,20.0,20.0,0.0,5.0,0,6.0,8.0,8.0,8.0,8.0,6.0,7.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,6.0,9.0,7.0,7.0,6.0,5.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
1,1,1.0,0,1,1,1,10,7,NaN,3,2,12.0,0,0.54,0,22.0,2.0,60.0,0.0,0.0,40.0,0.0,0.0,0,7.0,8.0,10.0,7.0,7.0,5.0,8.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,8.0,7.0,8.0,5.0,6.0,7.0,5.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
2,1,1.0,0,1,1,1,10,7,NaN,10,3,13.0,1,0.16,1,22.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,1,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,1.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,8.0,9.0,8.0,5.0,7.0,7.0,NaN,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
3,1,1.0,0,1,1,1,10,7,NaN,5,4,14.0,1,0.61,0,23.0,2.0,30.0,5.0,15.0,40.0,5.0,5.0,1,7.0,8.0,9.0,8.0,9.0,8.0,7.0,7.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,6.0,8.0,7.0,6.0,8.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
4,1,1.0,0,1,1,1,10,7,NaN,7,5,15.0,1,0.21,0,24.0,3.0,30.0,10.0,20.0,10.0,10.0,20.0,1,8.0,7.0,9.0,6.0,9.0,7.0,8.0,6.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,6.0,7.0,7.0,6.0,6.0,6.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN

In [17]:
df.describe(include='all')

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field,field_cd,undergra,mn_sat,tuition,race,imprace,imprelig,from,zipcode,income,goal,date,go_out,career,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3,match_label,race_label,goal_label
count,8378.000000,8377.000000,8378,8378.000000,8378.000000,8378.000000,8378.000000,8378.000000,6532.000000,8378.000000,8378.000000,8368.000000,8378.000000,8220.000000,8378.000000,8274.000000,8305.000000,8289.000000,8289.000000,8289.000000,8280.000000,8271.000000,8249.000000,8378.000000,8166.000000,8091.000000,8072.000000,8018.000000,7656.000000,7302.000000,8128.000000,8060.000000,7993.000000,8283.000000,8315,8296.000000,4914,3133,3583,8315.000000,8299.000000,8299.000000,8299,7314,4279,8299.000000,8281.000000,8299.000000,8289,8240.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8277.000000,1800.000000,8299.000000,8299.000000,8299.000000,8289.000000,8279.000000,8257.000000,6489.000000,6489.000000,6489.000000,6489.000000,6489.000000,6467.000000,8299.000000,8299.000000,8299.000000,8299.000000,8289.000000,8289.000000,8273.000000,8273.000000,8273.000000,8273.000000,8273.000000,4906.000000,4906.000000,4906.000000,4906.000000,4906.000000,8378.000000,8176.000000,8101.000000,8082.000000,8028.000000,7666.000000,7311.000000,8138.000000,8069.000000,8003.000000,7205.000000,4096.000000,4096.000000,4096.000000,4096.000000,4096.000000,4096.000000,4000.00000,4000.000000,4000.000000,4000.000000,4000.000000,7463.000000,7463.000000,7433.000000,1984.000000,1955.000000,1984.000000,1984.000000,1955.000000,1974.000000,7445.000000,7463.000000,7463.000000,7463.000000,7463.000000,7463.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.00000,5775.000000,5775.000000,5775.000000,5775.000000,7463.000000,7463.000000,7463.000000,7463.000000,7463.000000,4377.000000,4377.000000,4377.000000,4377.000000,4377.000000,3974.000000,3974.000000,3974.000000,1496.000000,668.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2016.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000,8378,8315,8299
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,259,NaN,241,68,115,NaN,NaN,NaN,269,409,261,NaN,NaN,NaN,367,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,5,6
top,NaN,NaN,Hommes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Business,NaN,UC Berkeley,"1,400.00","26,908.00",NaN,NaN,NaN,New York,0,"55,080.00",NaN,NaN,NaN,Finance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No Match,Européen/Caucasien,Se divertir
freq,NaN,NaN,4194,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,521,NaN,107,403,241,NaN,NaN,NaN,522,355,124,NaN,NaN,NaN,202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6998,4727,3426
mean,283.675937,8.960248,NaN,17.327166,1.828837,11.350919,16.872046,9.042731,9.295775,8.927668,8.963595,283.863767,0.164717,0.196010,0.395799,26.364999,2.756653,22.495347,17.396867,20.270759,17.459714,10.685375,11.845930,0.419551,6.190411,7.175256,7.369301,6.400599,6.778409,5.474870,6.134498,5.208251,1.960215,26.358928,NaN,7.662488,NaN,NaN,NaN,2.757186,3.784793,3.651645,NaN,NaN,NaN,2.122063,5.006762,2.158091,NaN,5.277791,6.425232,4.575491,6.245813,7.783829,6.985781,6.714544,5.737077,3.881191,5.745993,7.678515,5.304133,6.776118,7.919629,6.825401,7.851066,5.631281,4.339197,5.534131,5.570556,22.509466,17.387118,20.263039,17.451889,10.659827,11.835277,26.394360,11.071506,12.636308,15.566805,9.780089,11.014845,30.362192,13.273691,14.416891,18.422620,11.744499,11.854817,7.084733,8.294935,7.704460,8.403965,7.578388,6.941908,7.927232,8.284346,7.426213,7.617611,0.419909,6.189995,7.175164,7.368597,6.400598,6.777524,5.474559,6.134087,5.207523,0.948769,3.207814,20.791624,15.434255,17.243708,15.260869,11.144619,12.457925,7.21125,8.082000,8.257750,7.692500,7.589250,5.711510,1.843495,2.338087,32.819556,13.529923,15.293851,18.868448,7.286957,12.156028,26.217194,15.865084,17.813755,17.654765,9.913436,12.760263,26.806234,11.929177,12.103030,15.163810,9.342511,11.320866,29.344369,13.89823,13.958265,17.967233,11.909735,12.887976,7.125285,7.931529,8.238912,7.602171,7.486802,6.827964,7.394106,7.838702,7.279415,7.332191,0.780825,0.981631,0.376950,1.230615,0.934132,24.384524,16.588583,19.411346,16.233415,10.898075,12.699142,31.330357,15.654266,16.679563,16.418155,7.823909,12.207837,25.610341,10.751267,11.524839,14.276783,9.207503,11.253802,24.970936,10.923285,11.952687,14.959108,9.526191,11.966270,7.240312,8.093357,8.388777,7.658782,7.391545,6.810020,7.615079,7.932540,7.155258,7.048611,NaN,NaN,NaN
std,158.583367,5.491329,NaN,10.940735,0.376673,5.995903,4.358458,5.514939,5.650199,5.477009,5.491068,158.584899,0.370947,0.303539,0.489051,3.563648,1.230689,12.569802,7.044003,6.782895,6.085526,6.126544,6.362746,0.493515,1.950305,1.740575,1.550501,1.954078,1.794080,2.156163,1.841258,2.129354,0.245925,3.566763,NaN,3.758935,NaN,NaN,NaN,1.230905,2.845708,2.805237,NaN,NaN,NaN,1.407181,1.444531,1.105246,NaN,3.309520,2.619024,2.801874,2.418858,1.754868,2.052232,2.263407,2.570207,2.620507,2.502218,2.006565,2.529135,2.235152,1.700927,2.156283,1.791827,2.608913,2.717612,1.734059,4.762569,12.593915,7.037403,6.792025,6.079513,6.009535,6.352217,16.297045,6.659233,6.717476,7.328256,6.998428,6.060150,16.249937,6.976775,6.263304,6.577929,6.886532,6.167314,1.395783,1.407460,1.564321,1.076608,1.778315,1.498653,1.627054,1.283657,1.779129,1.773094,0.493573,1.950169,1.740315,1.550453,1.953702,1.794055,2.156363,1.841285,2.129565,0.989889,2.444813,12.968524,6.915322,6.596420,5.356969,5.514028,5.921789,1.41545,1.455741,1.179317,1.626839,1.793136,1.820764,0.975662,0.631240,17.155270,7.977482,7.292868,8.535963,6.125187,8.241906,14.388694,6.658494,6.535894,6.129746,5.675550,6.651547,16.402836,6.401556,5.990607,7.290107,5.856329,6.296155,14.551171,6.17169,5.398621,6.100307,6.313281,5.615691,1.371390,1.503236,1.180280,1.548200,1.744634,1.411096,1.588145,1.280936,1.647478,1.521854,1.611694,1.382139,0.484683,1.294557,0.753902,13.712120,7.471537,6.124502,5.163777,5.900697,6.557041,17.551540,9.336288,7.880088,7.231325,6.100502,8.615985,17.477134,5.740351,6.004222,6.927869,6.385852,6.516178,17.007669,6.226283,7.010650,7.935509,6.403117,7.012067,1.576596,1.610309,1.459094,1.744670,1.961417,1.507341,1.504551,1.340868,1.672787,1.717988,NaN,NaN,NaN
min,1.000000,1.000000,NaN,1.000000,1.000000,1.000000,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,-0.830000,0.000000,18.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,18.000000,NaN,1.000000,NaN,NaN,NaN,1.000000,0.000000,1.000000,NaN,NaN,NaN,1.000000,1.000000,1.000000,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000,1.000000,3.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,1.000000,0.000000,0.000000,3.00000,1.000000,4.000000,3.000000,2.000000,1.000000,1.000000,1.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,4.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000,1.000000,2.000000,2.000000,4.000000,1.000000,1.000000,NaN,NaN,NaN
25%,154.000000,4.000000,NaN,8.000000,2.000000,7.000000,14.000000,4.000000,4.000000,4.000000,4.000000,154.000000,0.000000,-0.020000,0.000000,24.000000,2.000000,15.000000,15.000000,17.390000,15.000000,5.000000,9.520000,0.000000,5.000000,6.000000,6.000000,5.000000,6.000000,4.000000,5.000000,4.000000,2.000000,24.000000,NaN,5.000000,NaN,NaN,NaN,2.000000,1.000000,1.000000,NaN,NaN,NaN,1.000000,4.000000,1.000000,NaN,2.000000,4.000000,2.000000,5.000000,7.000000,6.000000,5.000000,4.000000,2.000000,4.000000,7.000000,3.000000,5.000000,7.000000,5.000000,7.000000,4.000000,2.000000,5.000000,2.000000,15.000000,15.000000,17.390000,15.000000,5.000000,9.519048,10.000000,6.000000,8.000000,10.000000,5.000000,7.000000,20.000000,10.000000,10.000000,15.000000,6.000000,10.000000,6.000000,8.000000,7.000000,8.000000,7.000000,6.000000,7.000000,8.000000,6.000000,7.000000,0.000000,5.000000,6.000000,6.000000,5.000000,6.000000,4.000000,5.000000,4.000000,0.000000,2.000000,14.810000,10.000000,10.000000,10.000000,7.000000,9.000000,7.00000,7.000000,8.000000,7.000000,7.000000,5.000000,1.000000,2.000000,20.000000,10.000000,10.000000,10.000000,0.000000,5.000000,16.670000,10.000000,15.000000,15.000000,5.000000,10.000000,10.000000,8.000000,8.000000,9.000000,5.000000,7.000000,19.150000,10.00000,10.000000,15.000000,10.000000,10.000000,7.000000,7.000000,8.000000,7.000000,7.000000,6.000000,6.000000,7.000000,6.000000,6.000000,0.000000,0.000000,0.000000,1.000000,1.000000,15.220000,10.000000,16.670000,14.810000,5.000000,10.000000,20.000000,10.000000,10.000000,10.000000,0.000000,5.000000,10.000000,7.000000,7.000000,9.000000,5.000000,7.000000,10.000000,7.000000,7.000000,9.000000,6.000000,5.000000,7.000000,7.000000,8.000000,7.000000,6.000000,6.000000,7.000000,7.000000,6.000000,6.000000,NaN,NaN,NaN
50%,281.000000,8.000000,NaN,16.000000,2.000000,11.000000,18.000000,8.000000,9.000000,8.000000,8.000000,281.000000,0.000000,0.210000,0.000000,26.000000,2.000000,20.000000,18.370000,20.000000,18.000000,10.000000,10.640000,0.000000,6.000000,7.000000,7.000000,7.000000,7.000000,6.000000,6.000000,5.000000,2.000000,26.000000,NaN,8.000000,NaN,NaN,NaN,2.000000,3.000000,3.000000,NaN,NaN,NaN,2.000000,5.000000,2.000000,NaN,6.000000,7.000000,4.000000,6.000000,8.000000,7.000000,7.000000,6.000000,3.000000,6.000000,8.000000,6.000000,7.000000,8.000000,7.000000,8.000000,6.000000,4.000000,6.000000,4.000000,20.000000,18.181818,20.000000,18.000000,10.000000,11.000000,25.000000,10.000000,10.000000,15.000000,10.000000,10.000000,25.000000,15.000000,15.000000,20.000000,10.000000,10.000000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,8.000000,8.000000,0.000000,6.000000,7.000000,7.000000,7.000000,7.000000,6.000000,6.000000,5.000000,0.000000,3.000000,17.650000,15.790000,18.420000,15.910000,10.000000,12.500000,7.00000,8.000000,8.000000,8.000000,8.000000,6.000000,1.000000,2.000000,30.000000,10.000000,15.000000,20.000000,5.000000,10.000000,20.000000,16.670000,19.050000,18.370000,10.000000,13.000000,25.000000,10.000000,10.000000,15.000000,10.000000,10.000000,25.000000,15.00000,15.000000,18.520000,10.000000,13.950000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,7.000000,7.000000,0.000000,1.000000,0.000000,1.000000,1.000000,20.000000,16.670000,20.000000,16.330000,10.000000,14.290000,25.000000,15.000000,18.000000,17.000000,10.000000,10.000000,20.000000,10.000000,10.000000,12.000000,9.000000,10.000000,20.000000,10.000000,10.000000,15.000000,10.000000,10.000000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,7.000000,7.000000,NaN,NaN,NaN
75%,407.000000,13.000000,NaN,26.000000,2.000000,15.000000,20.000000,13.000000,14.000000,13.000000,13.000000,408.000000,0.000000,0.430000,1.000000,28.000000,4.000000,25.000000,20.000000,23.810000,20.000000,15.000000,16.000000,1.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,7.000000,7.000000,2.000000,28.000000,NaN,10.000000,NaN,NaN,NaN,4.000000,6.000000,6.000000,NaN,NaN,NaN,2.000000,6.000000,3.000000,NaN,7.000000,9.000000,7.000000,8.000000,9.000000,9.000000,8.000000,8.000000,6.000000,8.000000,9.000000,7.000000,9.000000,9.000000,8.000000,9.000000,8.000000,7.000000,7.000000,8.000000,25.000000,20.000000,23.080000,20.000000,15.000000,16.000000,35.000000,15.000000,16.000000,20.000000,15.000000,15.000000,40.000000,18.750000,20.000000,20.000000,15.000000,15.630000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,9.000000,9.000000,1.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,7.000000,7.000000,2.000000,4.000000,25.000000,20.000000,20.000000,20.000000,15.000000,16.280000,8.00000,9.000000,9.000000,9.000000,9.000000,7.000000,3.000000,3.000000,40.000000,20.000000,20.000000,24.000000,10.000000,20.000000,30.000000,20.000000,20.000000,20.000000,15.000000,16.670000,40.000000,15.000000,15.000000,20.000000,10.000000,15.000000,38.460000,19.23000,17.390000,20.000000,15.090000,16.515000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,8.000000,9.000000,8.000000,8.000000,1.000000,1.000000,1.000000,1.000000,1.000000,30.000000,20.000000,20.000000,20.000000,15.000000,16.670000,40.000000,20.000000,20.000000,20.000000,10.000000,20.000000,37.000000,15.000000,15.000000,20.000000,10.000000,15.000000,35.000000,15.000000,15.000000,20.000000,10.000000,15.000000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,8.000000,8.000000,NaN,NaN,NaN
max,552.000000,22.000000,NaN,44.000000,2.000000,21.000000,22.000000,22.000000,22.000000,22.000000,22.000000,552.000000,1.000000,0.910000,1.000000,55.000000,6.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,1.000000,10.500000,10.000000,10.000000,11.000000,10.000000,10.000000,10.000000,10.000000,8.000000,55.000000,NaN,18.000000,NaN,NaN,NaN,6.000000,10.000000,10.000000,NaN,NaN,NaN,6.000000,7.000000,7.000000,NaN,17.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,14.000000,10.000000,13.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,20.000000,100.000000,60.000000,50.000000,50.000000,35.810811,30.000000,95.000000,35.000000,35.000000,45.000000,50.000000,40.000000,100.000000,50.000000,40.000000,50.000000,50.000000,30.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,8.000000,18.000000,95.000000,50.000000,40.000000,40.000000,23.810000,30.000000,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,3.000000,3.000000,80.000000,40.000000,50.000000,50.000000,20.000000,40.000000,85.000000,50.000000,40.000000,50.000000,22.220000,35.000000,100.000000,35.000000,40.000000,50.000000,35.000000,40.000000,85.000000,40.00000,30.770000,40.000000,50.000000,30.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,21.000000,9.000000,1.000000,9.000000,4.000000,80.000000,65.000000,45.000000,30.000000,30.000000,55.000000,80.000000,60.000000,45.000000,40.000000,30.000000,55.000000,80.000000,40.000000,30.000000,30.000000,40.000000,45.000000,80.000000,50.000000,60.000000,40.000000,50.000000,45.000000,12.000000,12.000000,12.000000,12.000000,12.000000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,NaN,NaN

### Préparation des labels et normalisation

In [18]:
# Labels lisibles
df['gender'] = df['gender'].replace({1: 'Hommes', 0: 'Femmes'})
df['match_label'] = df['match'].map({0: 'No Match', 1: 'Match'})
df['race_label'] = df['race'].map({
    1: 'Black/African Am.', 2: 'Européen/Caucasien',
    3: 'Latino/Hispanic',   4: 'Asiatique',
    5: 'Natif Américain',   6: 'Autre'
})
df['goal_label'] = df['goal'].map({
    1: "Se divertir",           2: "Rencontrer des gens",
    3: "Obtenir un RDV",        4: "Relation sérieuse",
    5: "Pour l'expérience",     6: "Autre"
})

# Normalisation des critères de sélection sur 100 points
attr_cols = ['attr1_1', 'sinc1_1', 'intel1_1', 'fun1_1', 'amb1_1', 'shar1_1']

def normalize_row(row):
    total = row[attr_cols].sum()
    if total == 0:
        return row[attr_cols]
    return (row[attr_cols] / total) * 100

df[attr_cols] = df[attr_cols].apply(normalize_row, axis=1)

In [19]:
df.head()

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field,field_cd,undergra,mn_sat,tuition,race,imprace,imprelig,from,zipcode,income,goal,date,go_out,career,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3,match_label,race_label,goal_label
0,1,1.0,Femmes,1,1,1,10,7,NaN,4,1,11.0,0,0.14,0,27.0,2.0,35.0,20.0,20.0,20.0,0.0,5.0,0,6.0,8.0,8.0,8.0,8.0,6.0,7.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,6.0,9.0,7.0,7.0,6.0,5.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN,No Match,Asiatique,Rencontrer des gens
1,1,1.0,Femmes,1,1,1,10,7,NaN,3,2,12.0,0,0.54,0,22.0,2.0,60.0,0.0,0.0,40.0,0.0,0.0,0,7.0,8.0,10.0,7.0,7.0,5.0,8.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,8.0,7.0,8.0,5.0,6.0,7.0,5.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN,No Match,Asiatique,Rencontrer des gens
2,1,1.0,Femmes,1,1,1,10,7,NaN,10,3,13.0,1,0.16,1,22.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,1,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,1.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,8.0,9.0,8.0,5.0,7.0,7.0,NaN,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN,Match,Asiatique,Rencontrer des gens
3,1,1.0,Femmes,1,1,1,10,7,NaN,5,4,14.0,1,0.61,0,23.0,2.0,30.0,5.0,15.0,40.0,5.0,5.0,1,7.0,8.0,9.0,8.0,9.0,8.0,7.0,7.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,6.0,8.0,7.0,6.0,8.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN,Match,Asiatique,Rencontrer des gens
4,1,1.0,Femmes,1,1,1,10,7,NaN,7,5,15.0,1,0.21,0,24.0,3.0,30.0,10.0,20.0,10.0,10.0,20.0,1,8.0,7.0,9.0,6.0,9.0,7.0,8.0,6.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,6.0,7.0,7.0,6.0,6.0,6.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN,Match,Asiatique,Rencontrer des gens

## Qualité des données — Valeurs manquantes

Beaucoup de colonnes proviennent de questionnaires de suivi (J+1, J+30) qui n'ont pas tous été complétés.
On se concentre sur les variables du soir J, globalement bien renseignées.

In [4]:
missing_data = df.isnull().mean().sort_values(ascending=False).reset_index()
missing_data.columns = ['Variable', 'Pct_manquants']
missing_data = missing_data[missing_data['Pct_manquants'] > 0]

fig = px.bar(
    missing_data, x='Pct_manquants', y='Variable', orientation='h',
    title="Pourcentage de valeurs manquantes par variable",
    color='Pct_manquants', color_continuous_scale='Reds', height=1200
)
fig.show()

## 1. Qui sont les participants ?

Avant d'analyser les matchs, on dresse un portrait rapide de ceux qui ont participé à ces soirées.

### Genre

In [5]:
gender_counts = df.groupby('gender')['gender'].count().reset_index(name='count')

fig = px.pie(gender_counts, values='count', names='gender',
             title='Répartition par genre',
             color_discrete_sequence=['#636EFA', '#EF553B'],
             width=600, height=400)
fig.show()

### Âge

In [6]:
fig = px.histogram(df, x='age', color='gender',
                   title="Distribution de l'âge par genre",
                   labels={'age': 'Âge', 'gender': 'Genre'},
                   nbins=20, width=750, height=450)
fig.add_vline(x=df['age'].mean(), line_dash='dash', line_color='black',
              annotation_text=f"Moy. {df['age'].mean():.1f} ans",
              annotation_position='top right')
fig.show()

### Pourquoi sont-ils là ce soir ?

In [7]:
df_sun = df.groupby(['goal_label', 'match_label']).size().reset_index(name='nombre')

fig = px.sunburst(
    df_sun, path=['goal_label', 'match_label'], values='nombre',
    color='goal_label',
    title='Objectif de la soirée et résultat obtenu',
    width=750, height=750
)
fig.update_traces(textinfo='label+percent parent', insidetextorientation='radial')
fig.show()

**Interprétation :** La majorité des participants viennent pour "se divertir" ou "rencontrer de nouvelles personnes". Ceux qui cherchent explicitement un rendez-vous ou une relation sérieuse n'obtiennent pas un meilleur taux de match pour autant — l'intention déclarée n'a que peu d'impact sur le résultat.

## 2. Notre variable cible : le match

Un match se produit uniquement quand **les deux** participants disent "oui". C'est un événement rare.

In [8]:
match_counts = df['match'].value_counts().reset_index()
match_counts['label'] = match_counts['match'].map({0: 'No Match', 1: 'Match'})

fig = px.pie(
    match_counts, values='count', names='label',
    title=f"Taux de match global — {df['match'].mean()*100:.1f}% des speed dates aboutissent à un match",
    color='label',
    color_discrete_map={'Match': '#2ecc71', 'No Match': '#e74c3c'},
    width=600, height=400
)
fig.show()

In [9]:
taux_genre = df.groupby('gender')['match'].mean().reset_index()
taux_genre.columns = ['Genre', 'Taux de match']
taux_genre['Taux de match'] = (taux_genre['Taux de match'] * 100).round(1)

fig = px.bar(taux_genre, x='Genre', y='Taux de match',
             title='Taux de match par genre (%)',
             text='Taux de match',
             color='Genre',
             width=600, height=400)
fig.update_traces(texttemplate='%{text}%', textposition='outside')
fig.update_layout(showlegend=False)
fig.show()

**Interprétation :** Seulement ~16% des speed dates se terminent par un match. Hommes et femmes ont exactement le même taux — logique, puisqu'un match nécessite l'accord des deux. Ce taux de 16% sera notre référence tout au long de l'analyse.

---
## Question 1 — Qu'est-ce que chaque genre recherche, et qu'est-ce qu'il ne veut pas ?

Les participants répartissaient 100 points entre 6 critères selon leur importance dans le choix d'un partenaire. On regarde comment cette répartition diffère selon le genre.

In [10]:
attr_labels = {
    'attr1_1': 'Attractivité', 'sinc1_1': 'Sincérité',  'intel1_1': 'Intelligence',
    'fun1_1':  'Fun',           'amb1_1':  'Ambition',   'shar1_1':  'Intérêts communs'
}

attr_by_gender = df.groupby('gender')[attr_cols].mean()
attr_by_gender.columns = [attr_labels[c] for c in attr_cols]

attr_long = attr_by_gender.reset_index().melt(
    id_vars='gender', var_name='Critère', value_name='Poids moyen'
)

fig = px.bar(
    attr_long, x='Critère', y='Poids moyen', color='gender', barmode='group',
    title='Ce que chaque genre recherche chez un partenaire (sur 100 points)',
    labels={'Poids moyen': 'Poids moyen (pts)', 'Critère': '', 'gender': 'Genre'},
    color_discrete_sequence=['#636EFA', '#EF553B'],
    width=800, height=500
)
fig.show()

**Interprétation :** Les hommes placent l'attractivité physique loin devant (~27 pts), tandis que les femmes répartissent plus équitablement — sincérité, intelligence et fun arrivent presque au même niveau. **L'attribut le moins valorisé par les deux genres est l'ambition**, ce qui suggère qu'elle pèse peu lors d'un premier contact de 4 minutes. Pour les hommes, c'est aussi la sincérité qui est sous-cotée comparée aux femmes.

---
## Question 2 — L'attractivité est-elle aussi déterminante qu'on le croit ?

Les participants lui accordent beaucoup d'importance. Mais est-ce vraiment ce qui fait la différence entre un match et un non-match dans la pratique ?

In [11]:
# Écart de score entre Match et No Match pour chaque attribut
attributs = ['attr_o', 'sinc_o', 'intel_o', 'fun_o', 'amb_o', 'shar_o']
attr_names = {
    'attr_o': 'Attractivité', 'sinc_o': 'Sincérité',    'intel_o': 'Intelligence',
    'fun_o':  'Fun',           'amb_o':  'Ambition',     'shar_o':  'Intérêts partagés'
}

comp = df.groupby('match')[attributs].mean().T
comp.columns = ['No Match', 'Match']
comp['Différence'] = comp['Match'] - comp['No Match']
comp = comp.reset_index()
comp['index'] = comp['index'].map(attr_names)
comp = comp.sort_values('Différence', ascending=False)

fig = px.bar(
    comp, x='index', y='Différence',
    title="Écart de score entre Match et No Match — impact réel de chaque attribut",
    labels={'index': 'Attribut', 'Différence': 'Différence (Match − No Match)'},
    color='Différence', color_continuous_scale='Blues',
    width=750, height=500
)
fig.show()

In [13]:
# Le score "j'ai apprécié cette personne" (like_o) : prédicteur global
like_comp = df.groupby(['gender', 'match_label'])['like_o'].mean().reset_index()

fig = px.bar(
    like_comp, x='gender', y='like_o', color='match_label', barmode='group',
    title="'J'ai apprécié cette personne' — score moyen selon le résultat",
    labels={'like_o': 'Score moyen (sur 10)', 'gender': 'Genre', 'match_label': 'Résultat'},
    color_discrete_map={'Match': '#2ecc71', 'No Match': '#e74c3c'},
    width=700, height=450
)
fig.show()

**Interprétation :** L'attractivité a bien l'impact le plus fort sur le match (écart ~1,5 pt), suivie par le fun et les intérêts partagés. La sincérité et l'ambition ont l'effet le plus faible. Mais le vrai révélateur est le score global "j'ai apprécié cette personne" (`like_o`) : il passe de ~4,5 en non-match à ~7,5 en match. **L'alchimie perçue globalement prédit mieux le match que n'importe quel critère isolé**, y compris l'attractivité.

---
## Question 3 — Les intérêts partagés comptent-ils plus que l'origine raciale ?

In [ ]:
# Corrélation d'intérêts calculée objectivement par les chercheurs (int_corr)
int_corr_comp = df.groupby('match_label')['int_corr'].mean().reset_index()

fig = px.bar(
    int_corr_comp, x='match_label', y='int_corr',
    title='Corrélation des intérêts entre participants selon le résultat',
    labels={'int_corr': 'Corrélation moyenne des intérêts', 'match_label': 'Résultat'},
    color='match_label',
    color_discrete_map={'Match': '#2ecc71', 'No Match': '#e74c3c'},
    width=600, height=400
)
fig.show()

In [ ]:
# Comparaison directe des taux de match
taux_global = df['match'].mean() * 100

comparison_df = pd.DataFrame({
    'Facteur': ['Intérêts partagés
élevés (score ≥ 8)', 'Même origine
raciale'],
    'Taux de match (%)': [
        round(df[df['shar_o'] >= 8]['match'].mean() * 100, 1),
        round(df[df['samerace'] == 1]['match'].mean() * 100, 1)
    ]
})

fig = px.bar(
    comparison_df, x='Facteur', y='Taux de match (%)',
    title='Taux de match : intérêts partagés vs même origine raciale',
    text='Taux de match (%)',
    color='Facteur',
    width=650, height=450
)
fig.update_traces(texttemplate='%{text}%', textposition='outside')
fig.add_hline(y=taux_global, line_dash='dash', line_color='grey',
              annotation_text=f"Moyenne globale : {taux_global:.1f}%",
              annotation_position='top right')
fig.show()

**Interprétation :** La réponse est sans appel. Des intérêts partagés élevés (≥ 8/10) **doublent presque le taux de match** (~34% vs 16% en moyenne). En revanche, partager la même origine raciale n'apporte qu'un effet marginal (~17%, à peine au-dessus de la moyenne). La corrélation d'intérêts calculée objectivement confirme la même tendance. **Ce qu'on aime faire rapproche bien plus que d'où on vient.**

---
## Question 4 — Les participants se connaissent-ils eux-mêmes ?

Savent-ils comment les autres les perçoivent ? Et peuvent-ils prédire si ça va matcher ?

In [14]:
# Auto-évaluation de l'attractivité vs note réellement reçue
self_vs_real = df[['gender', 'attr3_1', 'attr_o']].dropna()

fig = px.scatter(
    self_vs_real, x='attr3_1', y='attr_o', color='gender',
    trendline='ols',
    title='Auto-évaluation vs note réellement reçue (attractivité)',
    labels={
        'attr3_1': 'Comment je me note (sur 10)',
        'attr_o':  'Comment les autres me notent (sur 10)',
        'gender':  'Genre'
    },
    opacity=0.25, width=700, height=500
)
# Ligne d'alignement parfait
fig.add_shape(type='line', x0=1, y0=1, x1=10, y1=10,
              line=dict(color='black', dash='dot', width=1))
fig.add_annotation(x=8, y=6.5, text="Alignement parfait →", showarrow=False,
                   font=dict(size=10, color='black'))
fig.show()

In [15]:
# Prédiction du match : est-ce que le partenaire "sent" le match venir ?
prob_comp = df.groupby('match_label')['prob_o'].mean().reset_index()

fig = px.bar(
    prob_comp, x='match_label', y='prob_o',
    title='Probabilité de match estimée par le partenaire vs résultat réel',
    labels={'prob_o': 'Probabilité estimée (sur 10)', 'match_label': 'Résultat réel'},
    color='match_label',
    color_discrete_map={'Match': '#2ecc71', 'No Match': '#e74c3c'},
    text='prob_o',
    width=600, height=400
)
fig.update_traces(texttemplate='%{text:.1f}', textposition='outside')
fig.show()

**Interprétation :** Le nuage de points se situe systématiquement **au-dessus** de la diagonale — les participants se surévaluent presque tous. Ce biais de positivité est présent chez les deux genres, légèrement plus marqué chez les hommes. Sur la prédiction, les participants qui ont obtenu un match s'y attendaient un peu plus (~5/10 vs ~3/10). Ils "sentent" quelque chose, mais l'écart reste faible : **on est de mauvais juges de notre propre valeur sur le marché de la séduction.**

---
## Question 5 — Vaut-il mieux être le premier ou le dernier speed date de la nuit ?

In [16]:
match_by_order = df.groupby('order')['match'].mean().reset_index()
match_by_order.columns = ['Position', 'Taux de match']
match_by_order['Taux de match'] = (match_by_order['Taux de match'] * 100).round(2)

fig = px.line(
    match_by_order, x='Position', y='Taux de match',
    title='Taux de match (%) selon la position dans la soirée',
    markers=True,
    labels={'Taux de match': 'Taux de match (%)'},
    width=750, height=480
)
fig.add_hline(
    y=df['match'].mean() * 100,
    line_dash='dash', line_color='red',
    annotation_text=f"Moyenne : {df['match'].mean()*100:.1f}%",
    annotation_position='top right'
)
fig.show()

**Interprétation :** Pas de tendance linéaire claire — ni les premiers ni les derniers ne sont systématiquement avantagés. On observe des variations autour de la moyenne sans pattern stable. L'effet de position est **minoritaire comparé aux critères personnels**. Si un conseil pratique est possible : éviter le milieu de soirée (positions 8–12) où le taux semble légèrement sous la moyenne, sans doute un creux d'attention.

---
## Conclusion

Cette analyse de 8 378 speed dates permet de répondre aux 5 questions initiales :

| # | Question | Réponse |
|---|---|---|
| 1 | Attributs les moins désirables | L'**ambition** est le critère le moins valorisé par les deux genres. Chez les hommes, la sincérité passe aussi loin derrière l'attractivité. |
| 2 | Attractivité vs réalité | Elle a bien le plus fort impact, mais c'est le **score global d'appréciation** (`like_o`) qui prédit le mieux un match. L'alchimie prime. |
| 3 | Intérêts partagés vs origine | Les **intérêts communs** ont un impact deux fois supérieur sur le taux de match (~34%) vs même origine (~17%). |
| 4 | Auto-perception | Les participants **surestiment** leur attractivité. Ils "sentent" vaguement un match possible mais restent de mauvais juges. |
| 5 | Position dans la soirée | L'effet est **limité**. Aucun slot n'est clairement avantageux. |

**Ce qui fait matcher deux personnes en 4 minutes : se plaire physiquement, avoir l'air de s'amuser, et partager des passions communes. Le reste suit.**